lr5/lr5/Controllers/HomeController.cs
using lr5.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lr5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MyDataService myDataService;

        public HomeController(ILogger<HomeController> logger, MyDataService my)
        {
            myDataService = my;
            _logger = logger;
        }

        public IActionResult Index()
        {
            int? userAuthed = HttpContext.Session.GetInt32("userAuthed");
            if (userAuthed.HasValue)
            {
                if(userAuthed == 1)
                {
                    return View();
                }
            }
            return RedirectToAction("Login", "Home");
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Reg()
        {
            int? userAuthed = HttpContext.Session.GetInt32("userAuthed");
            if (userAuthed.HasValue)
            {
                if (userAuthed == 1)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            string? userId = HttpContext.Session.GetString("userId");
            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public ActionResult HandleReg(string phone)
        {
            string? userId = HttpContext.Session.GetString("userId");
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { Success = false});
            }

            if(string.IsNullOrEmpty(phone)) return Json(new { Success = false });
            if(phone.Length != 9) return Json(new { Success = false });


            User targetUser = myDataService.GetUserById(userId);

            if (targetUser != null)
            {
                targetUser.phone = phone;
                myDataService.UpdateUser(userId, targetUser);
                HttpContext.Session.SetInt32("userAuthed", 1);
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }

        public async Task<IActionResult> Profile()
        {
            int? userAuthed = HttpContext.Session.GetInt32("userAuthed");
            if (!userAuthed.HasValue) return RedirectToAction("Login", "Home");
            if (userAuthed == 0) return RedirectToAction("Login", "Home");

            string? userId = HttpContext.Session.GetString("userId");
            if (string.IsNullOrEmpty(userId)) return RedirectToAction("Login", "Home");

            User targetUser = myDataService.GetUserById(userId);
            ViewBag.name = targetUser.name;
            ViewBag.email = targetUser.email;
            ViewBag.phone = "+380" + targetUser.phone;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lr5/lr5/Controllers/LabsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using lr5;
using Microsoft.AspNetCore.Authorization;

namespace lr5.Controllers
{
    public class LabsController : Controller
    {
        private readonly MyDataService myDataService;
        public LabsController(MyDataService my)
        {
            myDataService = my;
        }
        public ActionResult RunLab1()
        {
            return View();
        }
        public ActionResult RunLab2()
        {
            return View();
        }
        public ActionResult RunLab3()
        {
            return View();
        }

        [HttpPost]
        public ActionResult HandleRunLab1(string str1, string str2)
        {
            // Ваш код для обработки нажатия кнопки
            if(str1 == null || str2 == null)
            {
                return Json(new { success = false, error = "Не правильні параметри."});
            }

            int res1 = lr1.Solve(str1, str2);
            return Json(new { res1 });
        }

        [HttpPost]
        public ActionResult HandleRunLab2(int number)
        {
            try
            {
                int res1 = lr2.Resolve(number);
                return Json(new { res1 });
            }
            catch(Exception ex)
            {
                return Json(new { success = false, error = "Не правильні параметри." });
            }
        }

        [HttpPost]
        public ActionResult HandleRunLab3(int N, int x1, int y1, int x2, int y2)
        {
            try
            {
                int res1 = lr3.Search(N, x1, y1, x2, y2);
                return Json(new { res1 });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = "Не правильні параметри." });
            }
        }
    }
}

lr5/lr5/Controllers/OAuthController.cs
using IdentityModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;
using System.Text;
using static System.Formats.Asn1.AsnWriter;

namespace lr5.Controllers
{
    public class OAuthController : Controller
    {
        private readonly MyDataService myDataService;

        public OAuthController(MyDataService my)
        {
            myDataService = my;
        }
        public ActionResult RedirectToOAuthServer()
        {
            var scopes = new[]{"https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email"};
            string scope = string.Join(" ", scopes);

            string redirectUrl = $"https://localhost:5001/OAuth/Code";
            string verCode = Guid.NewGuid().ToString();
            string code = ComputeHash(verCode);

            HttpContext.Session.SetString("codeVerifier", verCode);

            var url = GoogleAuth.GenerateOAuthReqUrl(scope, redirectUrl, code);
            return Redirect(url);
        }

        public async Task<ActionResult> Code(string code)
        {
            string redirectUrl = "https://localhost:5001/OAuth/Code";
            string verCode = HttpContext.Session.GetString("codeVerifier");
            TokenResult resToken = await GoogleAuth.ExchangeCodeToToken(code, verCode, redirectUrl);
            if (resToken != null)
            {
                UserInfo res = await GoogleAuth.GetUserInfo(resToken.access_token);
                if (res != null)
                {
                    User targetUser = myDataService.GetUserById(res.Id);

                    HttpContext.Session.SetString("userId", res.Id);
                    HttpContext.Session.SetString("accessToken", resToken.access_token);
                    HttpContext.Session.SetInt32("userAuthed", 0);

                    if (targetUser == null || string.IsNullOrEmpty(targetUser.phone))
                    {
                        if (targetUser == null)
                        {
                            myDataService.AddUser(new User() { id= res.Id, name=res.Name, email=res.Email});
                        }
                        return RedirectToAction("Reg", "Home");
                    }
                    else
                    {
                        HttpContext.Session.SetInt32("userAuthed", 1);
                        return RedirectToAction("Index", "Home");
                    }
                }
            } 
            
            return RedirectToAction("Login", "Home");
        }

        public static string ComputeHash(string codeVerifier)
        {
            using var sha256 = SHA256.Create();
            var challengeBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(codeVerifier));
            var codeChallenge = Base64Url.Encode(challengeBytes);
            return codeChallenge;
        }
    }
}

lr5/lr5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Profile">Профіль</a>
    <h1 class="display-4">Лабораторні роботи 1, 2 та 3</h1>
    <ul>Виконати лабораторну роботу:
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="RunLab1">Lab1</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="RunLab2">Lab2</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="RunLab3">Lab3</a>
        </li>
    </ul>
</div>

lr5/lr5/Views/Home/Login.cshtml
@{
}

<div class="">
    <h1 class="display-4">Вхід</h1>
    <ul>
        <a class="nav-link" asp-area="" asp-controller="OAuth" asp-action="RedirectToOAuthServer">Вхід</a>
    </ul>
</div>

lr5/lr5/Views/Home/Profile.cshtml
@{
}

<div class="">
    <h1 class="display-4">Профіль</h1>
    <ul>
        <li class="nav-item">
            @ViewBag.name;
        </li>
        <li class="nav-item">
            @ViewBag.email;
        </li>
        <li class="nav-item">
            @ViewBag.phone;
        </li>
    </ul>
</div>

lr5/lr5/Views/Home/Reg.cshtml
@{
}

<h1>Для завершення реэстрації введіть номер телефону</h1>
+380
<input id="input1" type="number" pattern="[0-9]{8}" maxlength="8" />
<br />
<button id="myButton">Зареэструватись</button>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myButton").click(function () {
            $.ajax({
                url: "/Home/HandleReg",
                type: "POST",
                data: { phone: $("#input1").val()},
                success: function (data) {
                    if (data.success) {
                        window.location.href = "/Home/Index";
                    } else {
                        alert("Запрос не выполнен");
                    }
                }
            });
        });
    });
</script>